MENU = """
add              - used to add a phone number: "add [name] [phone]"
remove           - used to remove a phone number: "remove [name] [phone]"
change           - used to change a phone number: "change [name] [old phone] [new phone]"
phone            - used to display phone numbers: "phone [name]"
all              - used to display all contacts: "all"
add-birthday     - used to add a birthday: "add-birthday [name] [birthday]"
show-birthday    - used to display a birthday: "show-birthday [name]"
birthdays        - used to display birthdays that will happen in the next week: "birthdays"
remove-contact   - used to remove a contact: "remove-contact [name]"
hello            - used to display a welcome message: "hello"
close or exit    - used to close the program: "exit"
help             - used to display available commands: "help"
"""

__all__ = ["MENU"]
